FROM scratch
ADD rootfs.tar /
ENV ARCH=i386 CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.2.1511/isos/i386/CentOS-7-i386-Minimal-1511.iso QEMU_ARCH=i386

