FROM scratch
ADD rootfs.tar /
ENV ARCH=aarch64 CENTOS_VERSION=7.6.1810 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.6.1810/isos/aarch64/CentOS-7-aarch64-Minimal-1810.iso QEMU_ARCH=aarch64

