FROM scratch
ADD rootfs.tar /
ENV ARCH=x86_64 CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1601.qcow2 QEMU_ARCH=

