FROM scratch
ADD rootfs.tar /
ENV ARCH=x86_64 CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=ftp://ftp.free.fr/mirrors/ftp.centos.org/7.2.1511/isos/x86_64/CentOS-7-x86_64-Minimal-1511.iso QEMU_ARCH=

