FROM scratch
ADD rootfs.tar /
ENV ARCH=ppc64 CENTOS_VERSION=7.3.1611 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.3.1611/isos/ppc64/CentOS-7-AltArch-ppc64-Minimal-1611.iso QEMU_ARCH=ppc64

