FROM scratch
ADD rootfs.tar /
ENV ARCH=armv7l CENTOS_VERSION=7.6.1810 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.6.1810/isos/armhfp/CentOS-Userland-7-armv7hl-RootFS-Minimal-1810-sda.raw.xz QEMU_ARCH=arm

