FROM scratch
ADD rootfs.tar /
ENV ARCH=i386 CENTOS_VERSION=7.6.1810 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.6.1810/isos/i386/CentOS-7-i386-Minimal-1810.iso QEMU_ARCH=i386

