FROM scratch
ADD rootfs.tar /
ENV ARCH=ppc64 CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.2.1511/isos/ppc64/CentOS-7-AltArch-ppc64-NetInstall-1511.iso QEMU_ARCH=ppc64

