FROM scratch
ADD rootfs.tar /
ENV ARCH=armv7l CENTOS_VERSION=7.3.1611 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.3.1611/isos/armhfp/CentOS-Userland-7-armv7hl-Minimal-1611-CubieTruck.img.xz QEMU_ARCH=arm

