FROM scratch
ADD rootfs.tar /
ENV ARCH=aarch64 CENTOS_VERSION=7.3.1611 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.3.1611/isos/aarch64/CentOS-7-aarch64-rootfs-7.3.1611.tar.xz QEMU_ARCH=aarch64

