FROM scratch
ADD rootfs.tar /
ENV ARCH=ppc64le CENTOS_VERSION=7.6.1810 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.6.1810/isos/ppc64le/CentOS-7-ppc64le-Minimal-1810.iso QEMU_ARCH=ppc64le

