FROM scratch
ADD rootfs.tar /
ENV ARCH=armhfp CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.2.1511/isos/armhfp/CentOS-Userland-7-armv7hl-Minimal-1511-CubieTruck.img.xz QEMU_ARCH=arm

