FROM scratch
ADD rootfs.tar /
ENV ARCH=aarch64 CENTOS_VERSION=7.2.1511 DOCKER_REPO=multiarch/centos CENTOS_IMAGE_URL=http://mirror.centos.org/altarch/7.2.1511/isos/aarch64/CentOS-7-aarch64.img.xz QEMU_ARCH=aarch64

